name: JSON comments check

on:
  push:
#    paths:
#      - '**.jsonc'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: jsonc-syntax-check
        uses: stevieb9/jsonc-syntax-check@0.02
        with:
          pattern: "\\.jsonc$"